### ISSUE TITLE
Ideas/tweaks, that came to my mind

### ISSUE THREAD

**Issue by michaelmattle** [oliverschwendener/ueli#10]
Maybe you can implement following things:
* Possibility to (additionally to arrow keys) click on suggested items
* Easy way to access help, ex. press F1
* Easier way to define shortcuts like "g?", ex. wizard
* If no results are suggested for a search term, default suggest google or whatever defined

**Comment by kingnathanal** [comment]
Couple things I noticed:

When typing > ipconfig /all instead of >ipconfig /all , i get the following error:

![image](https://user-images.githubusercontent.com/1933426/38970410-51d32b9c-4363-11e8-843f-8de2e79183ec.png)

Also when I do >ipconfig /all  the terminal opens as expected but when I close ueli and reopen the terminal window is still there, should this close when closing ueli

Nice app been looking for something like Alfred since I switched to Windows

**Comment by oliverschwendener** [comment]
@kingnathanal Thanks for your feedback! I'm working on a fix. Please open up a separate issue for this bug.

**Comment by oliverschwendener** [comment]
Thank you for your feedback!

* Possibility to click on suggested items
    * Will be included in the next release
* Easy way to access help with F1
    * Will be included in the next release
* Easeier way to define shortcuts
    * You can edit your web searches in the config file. I hope to implement a nice GUI in the future to edit the configuration
* If no search results are suggested for a search term, default suggest google or whatever defined
    * I think this is unnecessary because if you want to google something you can type in `g?{whatever}`

**Comment by dschuessler** [comment]
Thank you for sharing your project with us.

I just wanted to weigh in that I don't deem it unnecessary to have a default fallback search. A few points on that:
- It is the default behavior of Alfred. So users like me, who search for an open source alternative to Alfred are already used to it.
- It guarantees that you can always leave ueli by hitting Enter, no matter what you typed. In other words: You can't get stuck with your search term, even if you hastily entered a typo. In the current state you have to first realize you made a mistake and correct your mistake or close the ueli window entirely to go on.

**Comment by khanhas** [comment]
Doesn't it feel weird when you hit enter, search term disappears and nothing runs. In Windows, a lot of applications don't run instantly, and most of the time I have to wait 2, 3 second before I can see any trace that they are running.  
So when I make a typo and search engine returns no result, I would like to know and type again correctly right away rather than waiting till I realize I make a mistake.

**Comment by oliverschwendener** [comment]
@dschuessler Thank you for your feedback! Alfred is great and I have copied many of it's features/behaviour to ueli. But I don't want to copy features or behaviour only because "Alfred users are used to it". And I don't get the point of the ability to "always leave ueli by hitting enter". What do you mean with "get stuck with your search term"?

**Comment by dschuessler** [comment]
@oliverschwendener: What I meant:
1. You type in what you search for.
2. You make mistakes while typing.
3. You get no results.
4. You blindly hit Enter.
5. Literally nothing happens.

@khanas: When there is a fallback search, it’s not that „nothing runs“, but you get web search results for the term you typed. The behavior I’d actually prefer is exactly, that Enter always does something and therefore always gives you feedback on what you just did. Button presses I expect to do something and then they surprisingly don’t, feel much „weirder“ to me personally.

I guess this is a matter of user experience and therefore my personal preference is of course not a sufficient reason to change the behavior of Ueli. I just wanted to bring to your attention that there are different preferences and usage patterns in this matter.

An ad hoc proposal for a customization option that would address the different preferences that were already voiced here:

```
"fallbackSearch": "Google"
```

Proposed behavior:
1. Invoke Ueli with Alt+Enter
2. Enter a term that corresponds to no internal search result from Ueli.
3. Hit Enter
4. A browser tab opens up and searches for the term on Google

By default there would be no fallback search set.

**Comment by oliverschwendener** [comment]
Published new version: https://github.com/oliverschwendener/ueli/releases/tag/v4.6.0
