### ISSUE TITLE
Advanced math toggle in Calculator plugin

### ISSUE THREAD

**Issue by Brugman** [oliverschwendener/ueli#1091]
I've figured out that I'm triggering the Calculator plugin quite often when I don't mean to.
```
or => OrcaSlicer
print => 3D Printing (folder shortcut)
to => Tools (folder shortcut)
```
![2024-04-23-19-08-48](https://github.com/oliverschwendener/ueli/assets/2203813/fc395228-e404-456f-9694-25ed52e3422f)
![2024-04-23-19-09-34](https://github.com/oliverschwendener/ueli/assets/2203813/fc687a85-67de-436f-8451-3c1016229bbc)
![2024-04-23-19-09-45](https://github.com/oliverschwendener/ueli/assets/2203813/854ed660-2089-4a89-8117-d3fd1cdf2148)

I also do a lot of _quick maths_, so I'd rather not disable the Calculator plugin entirely.

Could the Calculator plugin get a new setting to enable/disable "advanced" math?
Disabling would only do + - * / etc. Nothing with words.

**Comment by oliverschwendener** [comment]
Thanks for your feedback! We probably need a toggle or something similar that allows users to specify if they want functions to be a valid calculator result or not. That would probably solve this problem.

**Comment by oliverschwendener** [comment]
FYI we're currently working on ueli v9 where this issue seems to be fixed (see screenshot), so I consider this issue to be resolved. You can already download the alpha version here if you want to try it out: https://github.com/oliverschwendener/ueli/releases

![image](https://github.com/oliverschwendener/ueli/assets/15727229/0ae90ea7-4c73-49d0-a785-0abbdcc82c1b)
