### ISSUE TITLE
[Bug] Unable to run portable version without admin rights WIN11, installation is detected

### ISSUE THREAD

**Issue by designzwang** [oliverschwendener/ueli#1112]
**Describe the bug**

Not sure whether this is actually a bug or just a misinterpretation of the term "portable" on my side, but here goes:

I have downloaded and unzipped the latest Zip Archive labeled as "Portable "
https://github.com/oliverschwendener/ueli/releases/download/v8.29.0/ueli-8.29.0-win.zip

If I try to run the executable , I get the infamous “The app you’re trying to install isn’t a Microsoft-verified app” message.
Lacking admin rights, I can not disable the App Install Control Policy. This is why I use portable versions of important tools, and most of them work fine.

**Expected behavior**
Being able to run Ueli after unzipping the portable version, since it is supposed to be, well, portable :)

**Environment**
Win 11

**Additional context**
I am just getting started with my new Win11 machine and with  the new policies that are enforced on it , but at least I can run other applications that are truely portable, even big ones. So it seems as if something is happening that windows is seeing as an attempt to "install" - which should not happen for a portable version.
 I really love how Ueli helps me to get things done a lot faster on my old (win 10) , so I would like to continue using it. 
 
 Regards
Uli

**Comment by oliverschwendener** [comment]
This is because the application is not signed. You can find more details here:

- #974
- #193

In short: building an app that gets instant trust by the operating system costs a lot of money, and as this is an open source project that I don't get paid for, I don't want to spend any money on this. I hope to get the app into the Microsoft Store soon which should eliminate this issue.
