### ISSUE TITLE
[Feature Request]: rename "Blur" to "Focus loss"

### ISSUE THREAD

**Issue by Oneechan69** [oliverschwendener/ueli#1287]
Blur, that seems vague and doens't make sense. I was wondering how to make the ueli window not disappear after unfocusing it, and I got it by unchecking blur. Why is it called that? Should it be called something else like "window unfocus"?
<img width="854" alt="CleanShot 2024-12-06 at 22 38 56@2x" src="https://github.com/user-attachments/assets/005f7dae-912f-4d0c-b060-4c9a270ea256">

**Comment by oliverschwendener** [comment]
It is called "blur" because (at least in the web world) the event that happens when something loses focus is ofen called "blur". See these examples:

- https://developer.mozilla.org/en-US/docs/Web/API/Window/blur_event
- https://www.electronjs.org/docs/latest/api/browser-window#event-blur

But I agree, for people who are not familiar with this the term "blur" is quite confusing. I'll rename it to "focus loss" or something similar. Thanks for pointing out.

**Comment by oliverschwendener** [comment]
The next release will include a fix for this.
