### ISSUE TITLE
[Stupid question] what is the shortest way to search files, folders via ueli?

### ISSUE THREAD

**Issue by Droyk** [oliverschwendener/ueli#139]
Umm, this might seem like a really noob question but I have been using listary & everything to search for everything. thought to try something new like ueli.

So right now I am trying to search for my files & folders but it doesn't show me anything. Do I need to enable some settings to get it working? if so what setting?

I like to search my whole computer. I mean I have 4 drives name [C, D, E, F] I want ueli to provide the search results from all of my 4 drives. Is it possible?

**Comment by oliverschwendener** [comment]
My suggestion is **not** to use ueli to search your files, especially if you want to search your computer globally. But if you have some folders you access frequently you can add them in the section "file search" in the settings. Otherwise I suggest to use everything to search files globally.

If you already use everything to search your computer globally I have good news for you: currently I am working on a bigger update of ueli and it includes an optional everything plugin. Check this thread to learn more: #93
