### ISSUE TITLE
Multiple keys for hotKey combination

### ISSUE THREAD

**Issue by krizajb** [oliverschwendener/ueli#170]
If I understand correctly there is no possibility to use multiple keys for hotKey combination such as Shift+AltGr+Space as it was in the past? Could we make that possible again?

**Comment by dannyqwertz** [comment]
Is it possible to also allow free assignment of hotkeys (like e.g. Alt-X) again?

It would be awesome when letting the user record the hotkey (instead of using a dropdown menu) and checking the possibility to register this hotkey with a possible error message if this is limited within electron or the respective operating system.

**Comment by natyusha** [comment]
Is there a config file somewhere that can be edited to achieve this like in the old version?

**Comment by oliverschwendener** [comment]
@natyusha Yes there is a config file.

![image](https://user-images.githubusercontent.com/15727229/67089085-15dabd00-f1a7-11e9-92bf-32e4d16817ad.png)

**Comment by natyusha** [comment]
I looked in there when the new version was first released and it didn't seem like there was a way to add more than one modifier key so I rolled back to the previous version that supported it. In my case I wanted ctrl+shift+space to bring up the launcher.

**Comment by oliverschwendener** [comment]
This should now be possible with the latest version.
