### ISSUE TITLE
Everything Path should be escaped properly

### ISSUE THREAD

**Issue by pickbreaker** [oliverschwendener/ueli#172]
If the ES path contains spaces. The ES command is cant be executed. Maybe you should check if the path is properly escaped. Thanks for your ongoing work btw.

**Comment by oliverschwendener** [comment]
Thanks for your feedback! I added a fix which will be included in the next release.

**Comment by Chengers** [comment]
Hello Oliver, I wanted to bring to your attention that by putting double quotes around you've made it so that it literally executes the program making any search term an invalid argument which prompts the console help screen for "everything". 

`const command = `"${everythingSearchOptions.pathToEs}" -max-results ${everythingSearchOptions.maxSearchResults} ${searchTerm}`;`

In this case I think everything.exe is being executed with -max-results `everything.exe -max-results` instead of `everything.exe ${searchTerm} -max-results`. The solution is to rearrange it so that it executes the literal path with the argument searchTerm and with that plug in the extra arguments at the end. 

`const command = `"${everythingSearchOptions.pathToEs}" ${searchTerm} -max-results ${everythingSearchOptions.maxSearchResults}`;`  

Thanks for UELI by the way. Its my favorite windows program of 2019.

**Comment by sir-harlekin** [comment]
A question about everything integration. Is it possible to use UELI portable with Everything portable? I dont have admin rights on my office machine.

Kind regards

**Comment by Chengers** [comment]
Yes you can, just tried that on my standard user account.

**Comment by sir-harlekin** [comment]
Thanks. To be honest, i was to stupid to notice, that many plugins must be activated at first.

**Comment by computergeek125** [comment]
Adding on to this fun time (candidate for new bug?):

If the ES path now comes with quotes (like if the user did a Shift+Right Click > Copy as Path), the ES plugin can generate an error

```none
2020-02-09T17:27:57.920Z error: Command failed: ""C:\Program Files\Everything\es\es.exe"" -max-results 24 test
'""C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```
```
ueli 8.5.0
Electron 5.0.9
Node 12.0.0
V8 7.3.492.27-electron.0
```
