### ISSUE TITLE
Shortcut to server folder cannot be created

### ISSUE THREAD

**Issue by GitBiker** [oliverschwendener/ueli#189]
ueli version 8.1.1

settings
shortcuts
add shortcut
filetype "File path"
edit file path: "Choose folder" now navigate to \\server\folder1
save
-> invalid shortcut

**Comment by dwerne** [comment]
Workaround:

Create link to Networkdrive on harddisk and use SHORTCUT + FilePath.

**Comment by oliverschwendener** [comment]
I will close this issue because there is already a feature request for this: #145

**Comment by dwerne** [comment]
Hallo Oliver


Habe ein Problem mit Ueli und Everything:
[cid:image001.png@01D59546.4131A6C0]
Leider hat das log-file keine Einträge?

[cid:image002.png@01D59546.4131A6C0]

[cid:image003.png@01D59546.4131A6C0]

Gruss

Dominik

Von: Oliver Schwendener <notifications@github.com>
Gesendet: Mittwoch, 9. Oktober 2019 09:44
An: oliverschwendener/ueli <ueli@noreply.github.com>
Cc: Werne Dominik <werne@ibk.baug.ethz.ch>; Comment <comment@noreply.github.com>
Betreff: Re: [oliverschwendener/ueli] Shortcut to server folder cannot be created (#189)


I will close this issue because there is already a feature request for this: #145<https://github.com/oliverschwendener/ueli/issues/145>
