### ISSUE TITLE
Simple folder search seems to not be working in 8.1.2

### ISSUE THREAD

**Issue by TobiasDev** [oliverschwendener/ueli#192]
I updated this morning to the latest version of UELI and in this version I can't see any folders when I type the name of them (same name that I used to type to find them). I tried re-starting the plugin but it didn't help.

**Comment by oliverschwendener** [comment]
Can you show me the simple folder search settings you've made in the settings window?

**Comment by TobiasDev** [comment]
![image](https://user-images.githubusercontent.com/5912371/65027342-7671a280-d93a-11e9-8cec-ed79ddce1553.png)

**Comment by oliverschwendener** [comment]
Is there a hint in the debug log?

Here is how you open the debug log:

![image](https://user-images.githubusercontent.com/15727229/65058968-7347d800-d975-11e9-8226-7cb75743e8a8.png)

**Comment by TobiasDev** [comment]
Will check, sorry for the late reply

**Comment by TobiasDev** [comment]
I can't see anything about folders in the error log. The only error I see is this "2019-09-17T13:28:20.516Z error: stdout maxBuffer length exceeded", which I assume has nothing to do with folders?

**Comment by oliverschwendener** [comment]
This is exactly the issue. I'm looking into it asap!

**Comment by oliverschwendener** [comment]
Added a fix for this (included in the next release). The problem was that your file search tries to index alot of files (probably because one of your folders is searched recursively). I added a limit of 1000 files which fixed this issue but probably leads to files and folders which can't be found anymore. I suggest not using the recursive file scan too often. If you have big folders to be searched I suggest using the everything plugin.
