### ISSUE TITLE
Windows Defender blocks Ueli installation

### ISSUE THREAD

**Issue by Tobirexy** [oliverschwendener/ueli#193]
I don't know what's causing this and if anything can be done about it but I thought I'll let you know that Windows Defender blocks the start of the Ueli.exe.

It is possible to ignore this warning and run it anyway but I think this message will particularly scare off new users.
![image](https://user-images.githubusercontent.com/6097749/65013731-81b5d580-d91c-11e9-96f2-ba32959dca9c.png)

![image](https://user-images.githubusercontent.com/6097749/65013937-3f40c880-d91d-11e9-8605-5b9056781d64.png)

**Comment by oliverschwendener** [comment]
Thank you for your feedback! I am aware of this and this is documented in the [installation](https://github.com/oliverschwendener/ueli#installation) section of the readme. Both Windows and macOS prevent the first execution of ueli because it is not [code signed](https://en.wikipedia.org/wiki/Code_signing).

Why is ueli not code signed? Code signing an application on Windows requires a paid certificate and on macOS you need a Apple Developer ID which also costs 99$/year. At the current state I don't want to purchase either of these and I am totally OK with having the operating system blocking the app when opening the first time. I hope this answers your question :)

**Comment by oliverschwendener** [comment]
You can now get the app from the Microsoft Store here: https://apps.microsoft.com/detail/9pk44n42b2g7
