### ISSUE TITLE
Disable while playing fullscreen game

### ISSUE THREAD

**Issue by stefnotch** [oliverschwendener/ueli#237]
I have my Ueli shortcut set to `Ctrl`+`Space`, since the default `Alt`+`Space` shortcut is already used to open the window menu of most programs. This works perfectly, until I start video games where `Ctrl` (sneak/sprint/something) + `Space` (jump) is a pretty common keyboard combination. In fact, when playing videogames, lots of otherwise uncommon keyboard combinations suddenly get used.

So, I'd suggest something like an option to turn Ueli off while using a fullscreen application. Or while using certain applications.

**Comment by oliverschwendener** [comment]
There is no way for ueli to detect if you have another window opened in fullscreen mode. Just use a different keyboard shortcut if it collides with an existing keyboard shortcut in a game. Games don't disable keyboard shortcuts like the Windows key or `ctrl+shift+esc` either.

**Comment by Tenshi447** [comment]
Firstly, I don't mean to offend and my knowledge on coding is zero. But in Wox (open-source) and Listary there is an option to disable hotkey when fullscreen apps are active (foreground). This can also be achieved through AutoHotkey.

Since it is such a simple but useful feature to have, would you mind adding it in the future? With this UELI will be perfect. I've tried a lot of other similar apps but none has worked as great.

**Comment by oliverschwendener** [comment]
Thanks for letting me know, I'll see what I can do.
