### ISSUE TITLE
Application Search Broken on Windows 7

### ISSUE THREAD

**Issue by apaarfus** [oliverschwendener/ueli#244]
## Description

Now, I know, Windows 7 is EOL in about a month's time--but, hear me out.  I'm still on 7 (will be moving in a week to 10, though); but absolutely rely on `ueli` for almost everything application launch at this point.

Previously, on `ueli 7.2.7`, the application search appeared to be working correctly, allowing my application shortcuts within the global/local start-menu to be located without issue.  However, upon migrating to `ueli 8.4.1`, the application search is not longer pulling *anything* from my Windows 7 start menu's.

Furthermore, any attempt to rebuild the index leads to an extremely long process--which, unfortunately, does not yield any restored functionality.

I tried rolling back to my last-known-good version, 7.2.7, to no avail.  While it appeared to work at first, once I tried to actually launch an application; it crashed and was never able to recover--to the effect that restarting the application resulted in no systray icon or otherwise to allow me to test it; requiring me to kill the process manually from within Task Manager.

## Client Environment

- ueli Verison:  8.4.1
- Electron: 5.0.9
- NodeJS: 12.0.0
- JS V8: 7.3.492.27-electron.0
- OS: Windows 7 Professional x64

## Afterword

I realize this should no longer be an issue by 2020-01-14; however i figured it was worth bringing to your attention.  I suppose I can live without `ueli` for a week...gonna be a little strange, though.

**Comment by oliverschwendener** [comment]
Thanks for your feedback! Because it's hard enought to support Windows and macOS at the same time I don't want to make the effort and also support an old Windows version. This is why I'm going to close this issue now.

However you can try the following steps to get it working on Windows 7:
- Close ueli (from system tray or use Taks Manager)
- Uninstall ueli
- Delete the temporary folders
    - `C:\Users\<username>\.ueli`
    - `C:\Users\<username>\AppData\Roaming\ueli`
- Download the most recent version and install again
- Check if powershell is installed
