### ISSUE TITLE
Error when activating control panel

### ISSUE THREAD

**Issue by ToXIc-Dev** [oliverschwendener/ueli#296]
I get a user-service error when trying to enable the control panel plugin.

**Comment by oliverschwendener** [comment]
Thanks for reporting! Can you provide more information?

- What Windows version are you running?
- What version of ueli are you running?
- Can you provide us a screenshot of the error or even show us the debug log?

![image](https://user-images.githubusercontent.com/15727229/74815435-83375f80-52f9-11ea-8a7e-c05cafb22219.png)

@tkohlmeier

**Comment by ToXIc-Dev** [comment]
I am on Windows 10 Pro, Build 1903, running ueli version 8.5.2.

This is what comes up in the debug log when trying to enable control panel. the power button goes green, turning it on and off gives this error:

2020-02-21T11:37:28.025Z error: o.filter is not a function

**Comment by tkohlmeier** [comment]
Please open a command promt (cmd.exe) and run this command:
`powershell -Command "Get-ControlPanelItem | ConvertTo-Json" > output.txt`

Then please attach the file output.txt that is created by the command.

**Comment by tkohlmeier** [comment]
I just tried the current version of ueli and I can reproduce the problem with it. I will look into it.

**Comment by ToXIc-Dev** [comment]
[output.txt](https://github.com/oliverschwendener/ueli/files/4237724/output.txt)

Here you go.

**Comment by tkohlmeier** [comment]
That looks good.

@oliverschwendener: Is it possible to get stack traces of logged errors?

**Comment by oliverschwendener** [comment]
@tkohlmeier Not at the moment, sorry.

**Comment by tkohlmeier** [comment]
Alright, I extracted the code that probably causes the error to a single file. Please execute it with node.js so that we hopefully get more details.

1. Download Node.js 12 from here and install it:
https://nodejs.org
2. Download and extract the following zip file into an empty folder:
[controlPanelPluginTest.zip](https://github.com/oliverschwendener/ueli/files/4271082/controlPanelPluginTest.zip)
3. Open a command prompt and go to the folder where you extracted the zip file.
5. Execute: npm install
4. Execute: node index.js > output.txt
5. Attach the file output.txt that should have been created.

**Comment by ToXIc-Dev** [comment]
The file had the contents "successfully retrieved 40 control panel items".

**Comment by tkohlmeier** [comment]
I found out how to enable logging of stack traces and created a pull request (#309).
As soon as it is merged and released it will hopefully help to find the cause of this error.

**Comment by tkohlmeier** [comment]
The current version (8.6.1) contains the improved logging. Please update and try to enable the plugin again and then post the log file.

**Comment by ToXIc-Dev** [comment]
Control panel is now working as expected, no error now.

Thanks for the help.
