### ISSUE TITLE
Appearance in case of multiple desktops (screens / spaces) on Mac.

### ISSUE THREAD

**Issue by blmhemu** [oliverschwendener/ueli#303]
The launcher launches in the default screen (where it was originally launched). It does not appear in the current desktop / screen.
![ueli (1)](https://user-images.githubusercontent.com/19410501/75526385-b1264d80-5a37-11ea-9d07-257afc32f4ce.gif)

**Comment by oliverschwendener** [comment]
A fix for this will be included in the next release.

**Comment by oliverschwendener** [comment]
Thanks to @BenoitGour!

**Comment by blmhemu** [comment]
For people using [yabai](https://github.com/koekeishiya/yabai), use rule with stick=on
```yabai -m rule --add app=ueli                        sticky=on```

**Comment by oliverschwendener** [comment]
New release with a fix for this is out: https://ueli.app/#/download

**Comment by chunkhang** [comment]
Does anyone else still have issues with this? When I remove a desktop, the launcher forces the desktop to switch to Desktop 1 always.

**Comment by oliverschwendener** [comment]
@chunkhang Which version are you using?

**Comment by chunkhang** [comment]
> @chunkhang Which version are you using?

@oliverschwendener I'm on version 8.28.0.

**Comment by chunkhang** [comment]
@oliverschwendener Thanks for releasing v9. I'm now on v9.3.0, but this issue still persists. For me, these are the minimal steps to reproduce the problem on MacOS:

1. Have Desktop 1 and Desktop 2 ready
2. On Desktop 1, open Ueli app and window, then close it
3. On Desktop 2, open Ueli window

Ueli window will open in Desktop 1, rather than Desktop 2.

**Comment by oliverschwendener** [comment]
The next release will include a new option to control the window's visibility on multiple workspaces (virtual desktops)

![image](https://github.com/user-attachments/assets/0ca6c92c-dc3c-4eb4-998e-706dc67b30bc)

When you enable "Visible on all workspaces" it should solve the issue.

**Comment by oliverschwendener** [comment]
Feel free to reopen this issue if the next release won't fix the issue.

**Comment by chunkhang** [comment]
@oliverschwendener Thank you so much. It's working fine now.

**Comment by chunkhang** [comment]
@oliverschwendener 

I found another bug which may be related to the discussion. If you close a desktop in macOS, Ueli will always reopen in Desktop 1, instead of current desktop.

**Environment:**

- macOS Sonoma 14.4
- Ueli v9.6.0
  - "Visible on all workspaces" enabled

**Steps to reproduce:**

1. Have 3 desktops ready: Desktop 1, Desktop 2, Desktop 3
2. Open Ueli app (in any of the desktops)
3. Close Desktop 3
4. Open Ueli window in Desktop 2

**Current behavior:**

- Ueli window opens in Desktop 1

**Expected behavior:**

- Ueli window opens in Desktop 2
