### ISSUE TITLE
Thoughts about some feature requests

### ISSUE THREAD

**Issue by AmrBinBashir** [oliverschwendener/ueli#305]
**Khanhas's** fork of ueli is a lot outdated but it has a lot of features that's so useful and i was wondering about whether you would add them or at least consider adding them in the future so i know whether or not i should work on it my self and maybe make a pull request. 

**The features i'd like to see is as follows:**

**1-** Global hotkey for plugins. (for example: pressing Alt+S to open everything plugin so i can just start typing) .

**2-** Main window blur (it's just an aesthetic).

**3-** Ctrl + (number) to open the result item corresponding to the number, also when pressing Ctrl, it shows the numbers next to the title.

**4-** Add a search item for exesting windows open. (for example: if i have a firefox window open and i start searching for firefox, i would have two result items the first would be for switching to the exesting window and the other is for opening a new window) or we can add a new plugin for exesting menus that can be triggered by a prefix or a global hotkey like Khanhas did it.

**5-** Add an icon to each plugin that overrides the search icon when that plugin is active, i think it's a better UX.

**6-** Command line plugin suggestions as i type in the commands. i have an open issue about commands history #297  for the plugins and the suggestions can useful too. like if type `ipco` i would get result for `ipconfig` and result from previous entered commands.

Let me know your thoughts and which features of these you might consider adding them, i maybe able to help in some of these.

**Comment by oliverschwendener** [comment]
1) This is a nice idea, but I think this needs more thoughts. At the moment ueli is made up by two parts: search plugins and execution plugins. Search plugins just add items to a big list which is then searched when the user types in a search term (for example, application search, file/folder search). Execution plugins require some kind of prefix in order to be "activated" (for example websearch, commandline, etc.). Can the hotkey only be used for execution plugins or also for search plugins?

2) This can be implemented as soon as electron supports vibrancy for windows, currently it's macOS only. See here: https://www.electronjs.org/docs/api/browser-window

3) This can be implemented right now I think. The problem there is what happens if you have more than 9 results? You cant press "Ctrl+17" on your keyboard.

4) See #86. Difficulties here are:
- How can you check if there is already instance of this program running?
- How can you tell the program to launch a new window?
- How can you tell the operating system to set the focus on the existing window?
- How can you check if the program is only allowed to run as one instance. For example: you can't open Photoshop twice. If you try to launch the program it will set the focus on the already running instance if there is any.
- And of course everything has to be implemented on macOS and Windows

5) This is a good idea in my opinion, but can only be applied for execution plugins only.

6) Good idea.

In general, all good ideas but honestly I'm more focussed on building a plugin system so that I have only to maintain the core functionality and other people can build their own plugins.

**Comment by AmrBinBashir** [comment]
1- Yeah the hotkeys is for execution plugins only, because it would be kinda pointless for search plugins since i can already access that by "Alt+Space".

2- There is some unofficial ways to achieve that but it can be a headache, it's better to wait for electron's implementation i guess.

3- Only for the first 9 results or the 9 results that's is visible. 

4- This might need some cpp coding actually although there is some solutions out there for nodejs that i am experimenting with.

5- Yeah that's fine.

**Comment by Jarvvski** [comment]
Definitely keen on a plugin system. Would be great to add some more functionality ourselves and share them with the community

**Comment by kennethtxytqw** [comment]
The numbered shortcut please. I see the number but they dont seem to do anything but to show you the ranking.
