### ISSUE TITLE
[Feature Request] Shortcuts icons (simple folder search)

### ISSUE THREAD

**Issue by glat** [oliverschwendener/ueli#326]
I've a lots of shortcuts in a folder.
I added that folder to "Simple folder search" and I got results.
I opened this issue because I manually created shortcuts to a .exe file and I do not see the exe file icon but a simple white page icon.
Is it possible to assign to the shortcut icon the related .exe icon, such as Windows do for a shortcut?
Thanks

**Comment by femto-code** [comment]
Same issue when having `*.url` files in a folder which are Windows bookmark shortcut files leading to a website. In Ueli they do not appear with their icon.
I used Hain (alternative to Ueli but not continued) and it also shows the associated file icons of a certain file.

**Comment by glat** [comment]
I found a "workaround". Add your folder in "Application Search", and you'll get icons.

**Comment by femto-code** [comment]
> I found a "workaround". Add your folder in "Application Search", and you'll get icons.

Thank you very much @glat - your workaround did the trick!

**Comment by bee-eater** [comment]
I still like you request, because I use a lot of portable apps, which tend to have a launcher, and in a subfolder they have the actual application. Now I only want to get the launchers, so I added all my portable apps as "shortcuts" in Ueli, which leaves me without any icons. Also trying to set the .exe as icon doesn't work! 

@oliverschwendener 
Any chance to support .exe as Icon or try to get the icon from the file path automatically? Also a plugin for "PortableApps" would be quite handy, so the subfolders for a PortableApp would be ignored. Could also be done by a max. depth option for the Application Search folder entry?!

**Comment by bee-eater** [comment]
Currently I used a script to create a .ico for each .exe and used that in the settings for the Shortcuts.

[Extract icon from exe in Powershell](https://community.spiceworks.com/topic/592770-extract-icon-from-exe-powershell)

**Comment by oliverschwendener** [comment]
This should be solved with ueli v9.
