### ISSUE TITLE
Control Panel items seems to be always on top.

### ISSUE THREAD

**Issue by AmrBinBashir** [oliverschwendener/ueli#333]
No matter how many times I open vscode by just typing "v" i still have "Device Manager and Devices and Printers" always on top, same thing happened with "Steam" and "Sync Center".
Clearing the execution log doesn't help at all.

![image](https://user-images.githubusercontent.com/48618675/79053474-eda3b680-7c3d-11ea-88bd-8db60a335643.png)

**Comment by oliverschwendener** [comment]
Works fine for me. I guess you didn't open vscode that many times that it starts considering it as "more important" than "Device Manager" and "Devices and Printers".

![image](https://user-images.githubusercontent.com/15727229/78985483-37e74380-7b29-11ea-83fc-6f10f955ca3a.png)

**Comment by AmrBinBashir** [comment]
@oliverschwendener that's weird, I open vscode like 5 times a day at least. same thing with steam. I guess the issue only happens on my machine. Any thoughts about what might cause such an issue ?

**Comment by oliverschwendener** [comment]
Do you have the option "Log exection" enabled?

**Comment by AmrBinBashir** [comment]
Yes it's always enabled, and tried clearing the execution log a few days ago to reset everything but the issue still exist.

**Comment by tkohlmeier** [comment]
Sometimes I don't understand the suggestions either. For example:

![grafik](https://user-images.githubusercontent.com/6824291/79041206-36338380-7bee-11ea-8859-727980a4b02e.png)

I do open VS code often, but virtualbox is a perfect match for VirtualBox, so this should be suggested first.

**Comment by AmrBinBashir** [comment]
That's weird, your issue doesn't happen on my machine. And my issue doesn't happen on yours I assume. Maybe something is wrong with how ueli sorts the search results. It's gonna be hard to figure out the root of the problem.

**Comment by tkohlmeier** [comment]
I found a similar issue like yours, @AmrBinBashir:

![grafik](https://user-images.githubusercontent.com/6824291/79044017-178bb780-7c03-11ea-9daf-e5cbece1472a.png)

I opened Flash Player settings only two times but Firefox 110 times.

I think I found the reason. Fuse.js (which is used for the search) seems to largely increase the score for search results if a search item has multiple searchable texts that match the query. Each control panel item has two searchable texts, the name and the description. Since for the Flash Player both start with 'F', the score is very high: 0.000001 (lower is better). Firefox only has a score of 0.001. When I joined the two searchable texts of control panel items into one, the score dropped to 0.001, which makes much more sense.

We could always join the searchable texts into one. One downside of this approach is that fuse.js makes the score dependend on the location of the query within the searchable text. That's also the reason for my example with virtualbox. Since "Visual Studio Code" starts with "Visual" which is quite similar to "virtual", the score is higher than for "Oracle VM VirtualBox". I don't really like this behavior but I did not find an option to disable this. Anyway, this also means, that when we join the searchable texts, the latter texts are disadvantaged for the search.

Maybe there is an option in fuse.js to change this behavior? Or maybe a different search library would be better?

**Comment by AmrBinBashir** [comment]
@tkohlmeier Yeah, that seems reasonable regarding your issue with "virtual" and "visual" but for "Flash" and "Firefox" I don't think that's the case since Fuse matches the given input and outputs a list of items which is sorted by score but then Ueli sorts the same list again according to how many times an application is opened, which should sort Firefox and add to the top of the list.

**Comment by tkohlmeier** [comment]
> but then Ueli sorts the same list again according to how many times an application is opened

Yes, ueli improves the score by dividing with the number of executions * 3. So in my case the score for Flash Player is updated like this: 0.000001 / (2 * 3) = 0.0000001666...
And Firefox: 0.001 / (110 * 3) = 0.000003...
So the score for Flash Player is still higher, because the initial score difference is too big.

**Comment by AmrBinBashir** [comment]
Thanks for the explanation. I thought Ueli just sorts them directly without relying on fuse score.

In Wox, they had a feature " mark a search result as topmost in this query ". So if i searched with " v " and used this feature on " Visual studio code ", every time I use the same search query ( in this case " v " ) visual studio code will always be first but if i searched with another query the results are sorted normally. Maybe this approach is worth a try.
