### ISSUE TITLE
Icon not displaying correctly if a .lnk shortcut filename includes an opening square bracket: [

### ISSUE THREAD

**Issue by hi2u** [oliverschwendener/ueli#343]
I've got a number of Windows `.lnk` shortcuts that open my projects in either phpstorm or vscode. 

If the `.lnk` filename does NOT contain an square bracket, everything is fine, the correct `.lnk` icons are shown:

![good](https://user-images.githubusercontent.com/9689599/79631590-ad908680-819d-11ea-8264-87e1a90661d1.png)

But if the `.lnk` filename includes `[` (opening square bracket) - the icon doesn't display:

![2020-04-18_174836-ueli](https://user-images.githubusercontent.com/9689599/79631622-e6c8f680-819d-11ea-8e69-a2d7c7beae62.png)
![2020-04-18_174921-ueli](https://user-images.githubusercontent.com/9689599/79631626-edf00480-819d-11ea-92c1-ba3cc3264ba4.png)

Even stranger, it seems to also affect some other results for the same search too:

![2020-04-18_174858-ueli](https://user-images.githubusercontent.com/9689599/79631635-02340180-819e-11ea-87b8-bfde6f833432.png)

...note that the 2nd one `vscode tstest` doesn't even contain a `[` ... but the existence of `[` in a different shortcut `.lnk` file seems to affect the display both of them.

Closing square bracket `]` doesn't cause any problems.

Version numbers from the settings window:

* ueli: 8.6.2
* Electron: 8.1.1
* Node: 12.13.0
* V8: 8.0.426.26-electron.0

**Comment by tkohlmeier** [comment]
I found the problem and created PR #344 to fix this.

The square brackets were interpreted as wildcard characters and caused an error.

**Comment by oliverschwendener** [comment]
Should be fixed in the latest release.

**Comment by vivadavid** [comment]
Hi, I'm using Ueli 8.18.1 and I have a similar problem.

In Settings > Application Search > Add application folder, I've added a folder whose links aren’t recognized, probably because it contains square brackets [ ]:

C:\David\informática\[WINDOWS]\[CONFIGURACIÓN]\acceso rápido (quick access)\[ENLACES]

Adding a folder that contains (or whose path contains), for example, just accented characters (á, é, í, ó, ú) doesn't cause any problems, so I don't know which characters in particular are causing trouble here.
