### ISSUE TITLE
Ueli not searching for apps on windows help

### ISSUE THREAD

**Issue by Alexsh04** [oliverschwendener/ueli#349]
Hey, Ueli is not searching for apps in windows. if i search for chrome, photoshop which is installed in my pc, it doesnt shows them. im on windows 10 2004.

it also gives me an error when i try to reset it. please see the log.
[debug.log](https://github.com/oliverschwendener/ueli/files/4499180/debug.log)

**Comment by AmrBinBashir** [comment]
@Alexsh04 the log says that you don't have a desktop folder, open a powershell prompt and execute `ls ~` take a screenshot of the output, or just remove the desktop entry from your application search settings if you don't want to index your desktop folder.

**Comment by Alexsh04** [comment]
hey, 
I'm no developer, but i can say somethings wrong with ueli on my laptop. I reinstalled ueli couple of times, but it doesn't fix the problem.
Issue-

Until yesterday, ueli used to find me apps or desktop applications like chrome, photoshop, amazon music just by typing their name. I've not changed any settings or updated my device. But the problem started yesterday. It simply doesn't shows me all the applications on my laptop (not only chrome, photoshop etc.).

check the image, and powershell image.
![Annotation 2020-04-20 093729](https://user-images.githubusercontent.com/53342040/79713580-d9ba1d80-82eb-11ea-8f3a-e68eff9a6230.jpg)
![Annotation 2020-04-20 093833](https://user-images.githubusercontent.com/53342040/79713581-dc1c7780-82eb-11ea-8deb-12ee7e0b1aef.jpg)
![Annotation 2020-04-20 094115](https://user-images.githubusercontent.com/53342040/79713584-dd4da480-82eb-11ea-86e7-c888c40de69b.jpg)

**Comment by Fooughhy** [comment]
I am also having an issue similar to this. I have tried to open KeePassXC by adding THE ACTUAL FOLDER OF THE APPLICATION to the config. It still doesn't find it.
And now, for some reason, I am unable to launch anything.

I am using the "Everything" plugin, if that makes any difference.

**Comment by Alexsh04** [comment]
Update : I've reinstalled complete windows on my PC from scratch, but it still doesn't work. Can't search for applications like word, Excel etc.On Apr 20, 2020 11:27 AM, Fooughhy <notifications@github.com> wrote:
I am also having an issue similar to this. I have tried to open KeePassXC by adding THE ACTUAL FOLDER OF THE APPLICATION to the config. It still doesn't find it.
And now, for some reason, I am unable to launch anything.
I am using the "Everything" plugin, if that makes any difference.

**Comment by oliverschwendener** [comment]
Can you show us your application search settings?

**Comment by Alexsh04** [comment]
Yes. I've attached the image.
![Annotation 2020-04-20 150856](https://user-images.githubusercontent.com/53342040/79737410-e43edc00-8318-11ea-914a-92e609a0ff33.png)

**Comment by oliverschwendener** [comment]
According to your log file ueli can't find your Desktop folder. Try to remove it and check again.

**Comment by oliverschwendener** [comment]
> I have tried to open KeePassXC by adding THE ACTUAL FOLDER OF THE APPLICATION to the config. It still doesn't find it.

Do not add the folder that contains the actual application. Only add folders which contain shortcut files, for example: `C:\ProgramData\Microsoft\Windows\Start Menu`.

**Comment by Alexsh04** [comment]
yea, thanks. Its working now. 
And i went ahead and completely reinstalled windows, including all other apllications. Wasted my time.

but yea, such a wonderful application.
thanks developer.

**Comment by Fooughhy** [comment]
> > I have tried to open KeePassXC by adding THE ACTUAL FOLDER OF THE APPLICATION to the config. It still doesn't find it.
> 
> Do not add the folder that contains the actual application. Only add folders which contain shortcut files, for example: `C:\ProgramData\Microsoft\Windows\Start Menu`.

What?! Where does this say that it only uses shortcuts? I have MANY tools (batch scripts or things that are on my PATH) which I would like to have access to... Is this not possible?
I have included ".bat" and such in file-extensions, is this not valid?

And I have no "Desktop" folder in my config, so that is not interfering with anything. I am though getting errors in my logs about permissions as I include both "Program Files" folders on my C drive, and that include the Windows Defender install which has special permissions. Can the tool not handle failed permission checks? Should it not simply disregard that folder? 

One more thing, is there no blacklist which I can include the Windows Defender folder in? I understand OP got his issue fixed, but I have the same issue so I don't know why this was closed.

**Comment by AmrBinBashir** [comment]
Ueli can add .exe and .bat files, maybe Oliver meant it's best practice to add shortucuts of the programs you want in a folder and index that folder so ueil won't have trouble with permissions.

I would like a blacklist functionality too but for now if you want to index your Program Files you will have to launch Ueli as administrator.

**Comment by oliverschwendener** [comment]
@Fooughhy 
> I am though getting errors in my logs about permissions as I include both "Program Files" folders on my C drive, and that include the Windows Defender install which has special permissions. Can the tool not handle failed permission checks? Should it not simply disregard that folder?

Try to avoid adding such high level folders to the application folders. Try to only add folders containing shortcut files to applications because these folders are searched recursively.

I recommend:
- If you want to get quick access to certain files consider using the "Simple Folder Search" plugin.
- If you want to search your entire PC or entire disks consider using the "mdfind" plugin on macOS or the "Everything" plugin on Windows.

**Comment by Fooughhy** [comment]
I understand that, but could you tell me if the tool **fails** when there ere permission errors (for **all** files, that is)? That is the issue I have, that **no** executables are found, and I want to know if that is because of these errors.

**Comment by AmrBinBashir** [comment]
Yes, If there is one error within the paths you have in the application search plugin, Ueli won't index any application. 

This is inconvenient and should be fixed.
