### ISSUE TITLE
Scrolling issue due to arrow key selection.

### ISSUE THREAD

**Issue by weiw11** [oliverschwendener/ueli#355]
Hold the arrow key moves the selection down but if the selection reaches the end of the current view before the view scrolls, the selection think it reaches the end and goes back to the beginning of where it started, interrupting the scroll.

Example:
![gif](https://i.imgur.com/hbWdDKZ.gif)

Mouse clicks also have no affect on the drop down, but I'm not sure if that's intended.

Edit: Better gif

**Comment by AmrBinBashir** [comment]
This is called  "smooth scrolling", you can turn it off under appearance section in the settings.

**Comment by weiwang11** [comment]
Omg for letting me know. I didn't realize smooth scrolling was for the arrow keys since its typically used for mouse scroll. 

Is the current implementation suppose to work as shown in the gif though? I think it should at least continue down the list but slower rather than resetting to the top.

**Comment by AmrBinBashir** [comment]
The option is for the scroll whether by mouse or arrow keys and  yes the implementation is correct.

Ueli uses [scroll-behavior](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior) css property which has only two options `auto`and `smooth` and and as far as I know, there is no way to control the speed of the animation.

**Comment by weiwang11** [comment]
I think the issue is with the selection box as it thinks it reached the end of the list so it jumps back to the "beginning" since the scroll animation essentially goes to the "next page." The current implementation thinks it has already reached the end of the result list due to the scrolling animation.

There needs to be a scroll event handler for the selection to prevent inputs if the result view is scrolling. This way the selection won't jump to the "beginning" of the view as the current scrolling animation can be slower than selecting.

**Comment by AmrBinBashir** [comment]
> I think the issue is with the selection box as it thinks it reached the end of the list so it jumps back to the "beginning" since the scroll animation essentially goes to the "next page." The current implementation thinks it has already reached the end of the result list due to the scrolling animation.
>
The scrolling animation triggers after selection happens, so if you reach the last page of the results the scrolling animation begins but the selecting itself is much faster than the scroll animation so if you keep holding down, the selection goes to the first result which triggers another scroll animation that cancels the first and since the scrolling was in the opposite direction it makes it look like it's stuck.


>There needs to be a scroll event handler for the selection to prevent inputs if the result view is scrolling. This way the selection won't jump to the "beginning" of the view as the current scrolling animation can be slower than selecting.
>
Preventing the user from selecting after triggering animation can fix the issue but in the same time would be a bad UX to some users.

Honestly, I don't think anybody selects that fast in a real life situation.You should wait for oliver to respond, he is the one who can tell you whether he thinks it's a good idea or not.

**Comment by oliverschwendener** [comment]
In my opinion the current scroll behavior is intended and good enough for most scenarios.
