### ISSUE TITLE
ueli.app on macOS 10.15.4 banned

### ISSUE THREAD

**Issue by AWHubGit** [oliverschwendener/ueli#380]
ueli.app ueli-8.7.0.dmg on macOS 10.15.4 not running/launching. ueli.app classified/banned as unsafe coming from unknown(non-verified) developer.

**Comment by oliverschwendener** [comment]
This is normal behavior, because the app is not code signed and not notarized (for this you need an apple developer account and as far as I know this costs  $99/year). But you can force the operating system to open the app anyway via the system preferences.

![image](https://user-images.githubusercontent.com/15727229/81510929-f3141f80-9315-11ea-9155-1c0b6ae6f42d.png)
