### ISSUE TITLE
Command Prompt Encoding

### ISSUE THREAD

**Issue by Fry2412** [oliverschwendener/ueli#40]
Problems with encoding when characters like äöü should be displayed in the Windows command prompt.

Microsoft Windows [Version 10.0.17134.112]
ueli 4.7.0 - latest

**Comment by oliverschwendener** [comment]
Thanks for your feedback! Can you please provide more information? A screenshot with your input and commandline output visible would be very helpful.

**Comment by BlangTech** [comment]
I can provide one
![unbenannt](https://user-images.githubusercontent.com/2683790/42170892-1126e922-7e18-11e8-887b-af5b0a5ec40e.jpg)

The command was `>ping google.de`

**Comment by Fry2412** [comment]
Thanks for the quick attempt, but unfortunately the fix doesn't work on my machine.
It still looks like the screenshot provided by BlangTech.

Workaround: I set my system to English :D

Is the problem possibly in the ipcRenderer? If I understand that correctly, HTML is rendered by electron, isn't it?

**Comment by oliverschwendener** [comment]
You are right, my attempt does not work. I tested it with Windows set to German.

Yes the GUI is rendered by electron, but the problem seems to appear on a deeper level. When you start `ping` node spawns a new child process ([docs](https://nodejs.org/dist/latest-v8.x/docs/api/child_process.html#child_process_child_process_spawn_command_args_options)). Then when the spawned process writes data to the stdout stream it will be sent to the renderer (via the ipc module) which displays the data. But while debugging I noticed that the wrong encoding already appears when the stout stream is captured ([see here](https://github.com/oliverschwendener/ueli/blob/dev/src/ts/executors/command-line-executor.ts#L27)).

Apparently Windows uses other encoding than utf8 according to [this](https://stackoverflow.com/questions/20731785/wrong-encoding-when-using-child-process-spawn-or-exec-under-windows) post on stackoverflow.

Setting encoding to `utf8` doesn't seem to work either.

**Comment by BlangTech** [comment]
Windows-CMD is using CP850 (DOS Latin 1) encoding. I don't know if there is any decoder in Typescript for that, but you can maybe write your own ;-)
[CP850](http://www.gymel.com/charsets/CP850.html)
Mappingtable - `ftp://ftp.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/PC/CP850.TXT`

Then you can do something like that
`this.sendCommandLineOutputToRenderer(decodecp850(data.toString()));`

**Comment by oliverschwendener** [comment]
For the next release I added the possibility to add parameters to custom commands. So you could set up a custom command to directly launch commandline tools inside the windows command prompt.

Here is an example for the config file:

``` json
"customCommands": [
    {
        "name": "Open with cmd: ",
        "executionArgument": "!start cmd /K",
        "prefix": "cmd"
    }
]
```

This way you are able to type in `cmd ping 1.1.1.1` and `ping` will be started inside the windows command prompt and there shouldn't be any problems with encoding.
