### ISSUE TITLE
What's your thought about tauri framework ?

### ISSUE THREAD

**Issue by AmrBinBashir** [oliverschwendener/ueli#478]
Tauri is relatively new Framework that renders webtechnologies using webview apis on all platforms. It is similar to electron but the bundle size is way way smaller since It doesn't have to bundle chromium. 
The framework is still immature but it's promising. 
Do you think Ueli can migrate to Tauri in the future once it is stable and have all core functionality implemented, I mean Ueli can be bundled to probably a 5mb app ? 

Here is their [site](https://tauri.studio) and Here is an [app](https://guijs.dev/) built with it.

**Comment by KaKi87** [comment]
@amrbashir Why did you close this without waiting for an answer to your question ? 🤔

**Comment by oliverschwendener** [comment]
Sorry for taking 4 years to answer this question. Here are some reasons why I never considered switching to Tauri:

For me the downsides of electron were never big enough to migrate the codebase to Tauri. As far as I understand, correct me if I'm wrong, the frontend code can be HTML/JS/CSS/etc whatever works in a browser, but the backend code is Rust instead of Node.js, so I guess I would need to migrate the JS code from the main process to Rust. I'm also fine with a memory usage of 150Mb and an app size of 370Mb (on Windows). And after all I like using electron, there are constant updates with bugfixes, improvements, and new features. The people working on it are working on it full time and are paid, so to me it seems it's not something that will die anytime soon. Not sure how this is with Tauri, never looked that deep into it. And the time that I want to spend on this project is just not enough to learn a new framework, a new programming language and migrate all the code, just to make the app more lightweight. Even if I had the time to do all this, I would probably rather go with a WinUI3 app, just to make it really look "Windows-Like" and drop the Linux and macOS support as there are better tools for those platforms anyway, for example Raycast on macOS.

I hope this helped :)

**Comment by KaKi87** [comment]
> I would need to migrate the JS code from the main process to Rust

That's not always necessary, since Tauri has a [JS API](https://tauri.app/v1/api/js/) that aims to eventually achieve feature parity with Electron, although I don't know which ones Ueli currently depends on, so I can't say whether this project would currently need Rust code or not.

> I'm also fine with a memory usage of 150Mb

Are you still, now that Ueli will run on Linux ? One of the main reasons why people switch from Windows to Linux is it's lighter, and therefore provides a smoother user experience on entry-level and mid-range devices. Plenty of those people would love Ueli, but won't be able to afford it.

And even on devices that can afford it, launching an actual Chromium app to launch other apps sounds so overkill :/

> it's not something that will die anytime soon. Not sure how this is with Tauri

Tauri is a [well-funded non-profit organization](https://opencollective.com/tauri).

> drop the Linux and macOS support

:sob: 

> there are better tools for those platforms anyway

Not on Linux :/

**Comment by amrbashir** [comment]
> @amrbashir Why did you close this without waiting for an answer to your question? 🤔

Hey there, it was kind of weird and exciting to see a notification from this issue after so long time, a lot has happened since then that I never thought would happen. This project and this issue were the reason I discovered Tauri in the first place and now that I am core maintainer of Tauri, I am always grateful for this project.

I would like to apologize if I closed the issue impatiently, back then, I was a new developer and new to open source and I didn't comprehend the amount of work the people behind open source has put in, until I became one.

I am forever in debt to this project as my first ever contribution was to this project and this is where I learned about GitHub and open source, and even though I kind of stopped contributing to this project, I have always been following it closely and I appreciate the work @oliverschwendener has put into this project.

**Comment by amrbashir** [comment]
As a Tauri maintainer now, it is hard to be impartial, but I will say this at least, we are constantly working hard to push bug fixes and new features and not going to die any time soon either.

I know now that migrating to a new framework and a new language takes a tremendous amount of work so I would never ask anyone to migrate, but if you ever decide in the future to migrate, I would love to help in any way I could. I know that Ueli could benefit from a fast language like Rust specially when indexing apps and such but not something that warrants a full rewrite IMO.

**Comment by oliverschwendener** [comment]
@KaKi87 

> That's not always necessary, since Tauri has a [JS API](https://tauri.app/v1/api/js/) that aims to eventually achieve feature parity with Electron, although I don't know which ones Ueli currently depends on, so I can't say whether this project would currently need Rust code or not.

The majority of ueli's code is running in electron's main process and therefore depends on not only electron's API but also the Node.js API, so I guess that eventually some code needs to be rewritten in Rust.

> Are you still, now that Ueli will run on Linux ?

Yes.

> One of the main reasons why people switch from Windows to Linux is it's lighter, and therefore provides a smoother user experience on entry-level and mid-range devices. Plenty of those people would love Ueli, but won't be able to afford it.

Then I'm sorry. I never promised that this app is the most lightweight or most efficient or best option for everyone. Electron works just fine for me, and therefore I'll continue using it. We even have [a section in the readme](https://github.com/oliverschwendener/ueli/tree/v8.28.0?tab=readme-ov-file#alternatives) that points to alternatives.

> And even on devices that can afford it, launching an actual Chromium app to launch other apps sounds so overkill :/

Yes, because it is overkill. If you just want to launch apps and find an electron app overkill, then just use the operating system's built in app launcher. Every Linux distro that I tried so far had one. If you're not happy with that either go find a tool that suits your needs, or build one yourself, as I did.

> Tauri is a [well-funded non-profit organization](https://opencollective.com/tauri).

Good for them. But this doesn't make me learn a new language, framework and migrate all the code.

> 😭

Calm down, I'm not going to drop the Linux and macOS support. This is just a thought about what I would do if I wanted to prioritize efficiency above all else, which at the moment is not the case.

> Not on Linux :/

Then I'm sorry that this project is not what you're looking for.

---

Look, the question in this thread was about "my thoughts about using tauri" and "switching to tauri for this project" and I shared my thoughts about it and that I'm currently happy with electron, even if I can't satisfy the needs of some users who have a focus on "lightweightness" and efficiency. I don't say Tauri is bad or that Electron is better. All I'm saying is that currently I'm not willing to switch because the effort needed exceeds the time that I want to spend on this project. It's that simple. If you think Tauri is the better option, please feel free to do a fork (and take 7 years of work for free, you're welcome) and do it yourself or find a group of people who want to do it. This is the beauty of open source ;)

**Comment by oliverschwendener** [comment]
@amrbashir Thank you for your kind words, it means a lot to me! I'm happy for you and I wish you and the Tauri team all the best.
