### ISSUE TITLE
Portable version not portable

### ISSUE THREAD

**Issue by teamayu** [oliverschwendener/ueli#496]
I assume because of Electron, but lots of info stored in the appData folder:

AppData/Roaming/ueli

And also in the user folder:

Users\XXX\.ueli

Anyway to disable these?

**Comment by femto-code** [comment]
@teamayu This is a normal behaviour because of the way Electron works. It stores its environment data necessary for running under Windows in `AppData\Roaming` and recreates it again if you remove it or if you start Ueli on another device. The data under `Users\XXX\.ueli` is just cache and debug data and therefore not necessary for keeping relevant user settings neither.
"Portable" just means that the executables aren't in the system folders. You can run them anywhere you want.

**Comment by teamayu** [comment]
No problem. The portable version at portapps.io is better, but still creates an appdata folder and the user folder. To be honest, there are better launchers around that are natively portable with no trace, so even though Ueli is a clean piece of software, I'll give it a miss for now.

**Comment by oliverschwendener** [comment]
I see your point. At the moment there is no way to disable the temporarily created folders/files. Thanks for your feedback!

**Comment by david-maus** [comment]
I think you can edit the userData Path?
Something like:

`if (isDevelopment) {
    app.setPath('userData', path.join(__dirname, 'config'))
} else {
    app.setPath('userData', path.join(path.dirname(process.execPath), 'config'))
}`

**Comment by derei** [comment]
PortableApps platform is able to run apps without leaving any trace on the host computer. It uses its own temp folders. Maybe it would be worth looking into that one to see how it works and how an app can be made to comply with the same policy.
I agree that a PORTABLE app should be completely portable and when the app is not in use, it should remove all its traces from the host machine.

**Comment by alabotski** [comment]
Can we set own data folder for settings?

**Comment by oliverschwendener** [comment]
I see that the "portable" version is fully portable in that sense. But as this is not a priority at the moment I'll close this issue.
