### ISSUE TITLE
Windows: Incorrect userprofile path usage

### ISSUE THREAD

**Issue by FroyoXSG** [oliverschwendener/ueli#510]
A quick look into the debug log shows that ueli is not using the correct way to specify userprofile-related paths.
For example, if I set my Desktop under `D:\Users\froyo\Desktop`, you won't be able to find it via `C:\Users\froyo\Desktop`.
(Edit: the next sentence is wrong:) The correct usage is `%userprofile%\Desktop`

**Comment by AmrBinBashir** [comment]
@FroyoXSG As far as I know ueli uses nodejs [os.homedir](https://nodejs.org/api/os.html#os_os_homedir) and it determines the userprofile through `%userprofile%` variable.

So in theory, as long as `%userprofile%` variable redirects you to the correct user profile directory, ueli should have nothing to complain about.

Do you mind posting the debug logs, so I can take a look ?

**Comment by FroyoXSG** [comment]
Looks like this is more complicated than I thought.
You see, my `%userprofile%` is actually on `C:\`, but most other folders are moved via the properties tabs.
When you go to `%userprofile%\Desktop` or `C:\Users\froyo\Desktop` via Windows Explorer's address bar, it correctly redirects you to `D:\Users\froyo\Desktop`. However, this redirect doesn't work from cmd.exe, for instance.

**Comment by FroyoXSG** [comment]
@AmrBinBashir Sure, here's the logs
```
Cannot find path 'C:\Users\fabia\Desktop' because it does not exist.
2020-09-05T17:46:55.324Z debug: 512/513 app icons already exist
2020-09-05T17:46:55.324Z debug: Started to generate 1 app icons to C:\Users\fabia\.ueli\application-icons
2020-09-05T17:46:58.302Z debug: Successfully generated 1 icons
2020-09-05T17:47:01.780Z debug: Successfully refreshed all indexes
2020-09-05T17:54:24.053Z error: Other instance is already running: quitting app.
2020-09-05T17:54:55.170Z debug: Check for updates
2020-09-05T17:54:56.976Z debug: Update check result: update not available
```

**Comment by FroyoXSG** [comment]
[This seems to be the most up-to-date Microsoft documentation for this stuff](https://docs.microsoft.com/en-us/windows/win32/shell/knownfolderid). No idea if nodejs already incorporates this. 
Anyway, sorry for such a nitpick bug report. I expected the solution to be simpler 😅

**Comment by AmrBinBashir** [comment]
I see, Let me explain how ueli finds the desktop folder, Ueli calls `os.homedir` which will use windows's `%userprofile%` variable and that would return in your case `C:\Users\fabia` then Ueli adds `\Desktop` to the end. Now, In your case what happens is Ueli uses powershell to list what's in the Desktop folder at the path determined by the process above, and powershell reports that the given path doesn't exist and that's true. 

File Explorer keeps track of the known folders location somehow and redirects you correctly. 
The location of these folders can be accessed using native tools, but that would make the development harder than it should be, since Ueli only uses this folder as a default location for the application search plugin which can simply be removed by the user if causes issues. 

Your situation is very specific to be honest and In my opinion, this doesn't qualify to be a bug.
The simplest solution for people who changed their Desktop folder location is simply removing it from the application search plugin and adding the correct path. You will have to set it up once and forget about it.

**Comment by FroyoXSG** [comment]
Feels like the ball is in nodejs's court.
@oliverschwendener I'm closing this
