### ISSUE TITLE
Command prompt not showing up when I type in "CMD"

### ISSUE THREAD

**Issue by siddarththiru** [oliverschwendener/ueli#522]

**Comment by oliverschwendener** [comment]
Try searching for "Command prompt"?

The reason why Command Prompt is not showing up as a search result is because there is no shortcut file with the name "CMD" in your start menu folders. Somehow the windows search knows magically that CMD means Command prompt and that's why it is showing up in there but ueli can't recognize it.

As a workaround you can create a shortcut with the name "cmd" that points to the right shortcut file / executable.

**Comment by walter6469** [comment]
Ok thanks!

**Comment by walter6469** [comment]
What if it was through run commands? Just a guess btw

**Comment by SwedishChef** [comment]
I'm not sure if this is same issue but:

Typing "cm(d)" finds "cmd.exe" but after pressing enter ueli hangs and has to be restarted.

![image](https://user-images.githubusercontent.com/33290635/147066841-d46cfb56-857d-43a9-9aa1-d1a705bf0cce.png)
