### ISSUE TITLE
Avoid Freezing when Refreshing Index

### ISSUE THREAD

**Issue by GovindKrishnan** [oliverschwendener/ueli#562]
Hi

Just wanted to know if you can let Ueli use the old index till refreshing of index is complete in background?

While I was hurriedly searching something, it froze awaiting a refresh of the index

Sometimes, this can suddenly interrupt our flow.

I ain't a programmer yet. But would be cool if Ueli can temporarily use old index if we're using it while new index is being built in background.

Thanks 👍

**Comment by standerksen** [comment]
I second this. One of the main reasons why I have turned of periodic rescan. This could be fixed by either canceling the reindexing process when the ueli search bar is called or as requested above by using the old index on the search bar while it is being updated in the background.

I took me a while to get all settings set the first time because I had to keep waiting for it to be finished indexing.

**Comment by oliverschwendener** [comment]
This should be solved now with the latest update.
