### ISSUE TITLE
Refreshing indexes after adding item to blacklist doesn't apply blacklist

### ISSUE THREAD

**Issue by MonstraG** [oliverschwendener/ueli#623]
Using blacklist while https://github.com/oliverschwendener/ueli/issues/611 is not available.

1. Find something you want not to appear
2. Add it's path to blacklist
3. Refresh indexes
4. Search for it again - it's here.

![1](https://user-images.githubusercontent.com/17963791/104156434-da12bf80-540a-11eb-83af-5ca2f3d969b5.gif)
Every time explorer gets focused - I press Ctrl+O to open exe's folder.

**Comment by oliverschwendener** [comment]
What happens if you just enter the filename instead of the full path?

**Comment by MonstraG** [comment]
![image](https://user-images.githubusercontent.com/17963791/104161408-a0df4d00-5414-11eb-9574-1f0ca9acda90.png)

Same thing, it still finds it

**Comment by oliverschwendener** [comment]
I mean when you add just the filename in the blacklist.

**Comment by MonstraG** [comment]
Works with "rider64", doesn't work with "rider64.exe"

**Comment by oliverschwendener** [comment]
Sorry for the confusion! Is this resolved now?

**Comment by MonstraG** [comment]
Technically not, since I would like for blacklist to be able to ignore directories, but if this works as intended, it would be a feature request not a bug.

**Comment by oliverschwendener** [comment]
For now this works as intended. You can exclude items by filename. There is a feature request/enhancement for improving the exclusion of items by adding patterns: https://github.com/oliverschwendener/ueli/issues/611

From what I see I assume that you have added the folder `F:\Programs` to the application search folders. It's not recommended to add such high level folders to the applicaiton search because now these folders are searchred recursively which ends up with very poor reindex performance. For applications it's recommended to add only folders which contain shortcut files.
