### ISSUE TITLE
periodic rescan stalls system

### ISSUE THREAD

**Issue by xmrv** [oliverschwendener/ueli#719]
So I was playing BF4 today and these stalls drove me almost crazy. Fortunately I tracked down the problem and it was ueli, more specifically periodic rescan. It stalls the system through powershell so much that cpu usage spikes up to a hundred, game lags, inputs become non-responsive etc.

edit: cpu: 7700k@4.4ghz

**Comment by tkohlmeier** [comment]
Could you post the command line of that powershell process?

**Comment by Blacktail92** [comment]
Yes it does.

**Comment by Blacktail92** [comment]
Understandable. Have a nice day then :)

**Comment by oliverschwendener** [comment]
Is this resolved?

**Comment by Blacktail92** [comment]
Nope.

**Comment by Fooughhy** [comment]
This was driving me crazy, as I believe the default period was quite low. I've had it at 1 hour now which is more manageable.

But the usage is still completely unacceptable, sadly. Is there any way, or any plan, to cap the CPU usage of it somehow? Or simply throttle it or something?

I've had trouble with this before, as the search in this application seems unbelievable unoptimized or does a LOT of extra work. That's of course very possible since I don't know what's going on under the hood. But if I were to use a tool such as [fd](https://github.com/sharkdp/fd) to search in the same way that ueli search (though I'm even taking the parent directory of some of my paths even, in the 'fd' case) it literally takes 3 seconds. 

So for example, I have these paths:
![image](https://user-images.githubusercontent.com/6977416/140608376-4f425a1d-b493-48d6-ab3e-f553c7383ab1.png)

And the file-types 'exe', 'ink', 'appref-ms' and 'ps1'.

This command in 'fd' searches much more as at least two paths are parents of one in the 'ueli' case:
`fd -e 'exe' -e 'ink' -e 'appref-ms' -e 'ps1' --search-path "C:/ProgramData/chocolatey/" --search-path "C:/Users/fough/AppData/Roaming/Microsoft/Windows/Start Menu" --search-path "C:/Users/fough/Documents/" --search-path "C:/ProgramData/Microsoft/Windows/Start Menu/" --search-path "C:/Users/fough/scoop/" --search-path "c:/tools" --search-path "C:/Users/fough/Desktop" .`

This search takes 3 seconds. No CPU usage, no memory usage (essentially).

**Comment by Fooughhy** [comment]
Sad that such a big issue didn't get any attention. Has the performance been improved in the last year?

**Comment by oliverschwendener** [comment]
Please check out the latest alpha release and reach out if the issue still persists:

https://github.com/oliverschwendener/ueli/releases/tag/v9.0.0-alpha.3

**Comment by oliverschwendener** [comment]
CLosing due to inactivty
