### ISSUE TITLE
[Bug] Workflows opens Windows Terminal instead of default CLI

### ISSUE THREAD

**Issue by firinael** [oliverschwendener/ueli#758]
As described in the title, when executing a command line through Workflows, the command is executed in a Windows Terminal window instead of my default (which is cmd).

EDIT: Closing and reopening ueli seems to have updated the preferred CLI, and it's now targeting cmd. Seems it's a case of it not updating while running?

**Comment by oliverschwendener** [comment]
Do you have cmd set as your shell in the commandline settings?

![image](https://user-images.githubusercontent.com/15727229/123503993-c1176700-d656-11eb-8123-24a4aaa608a2.png)

**Comment by firinael** [comment]
Yep, using cmd as default.

**Comment by oliverschwendener** [comment]
This will be fixed with ueli v9. You can try out the latest beta release here: https://github.com/oliverschwendener/ueli/releases.

In ueli v9 you can choose which Terminal you want to launch in your workflow:

![image](https://github.com/oliverschwendener/ueli/assets/15727229/1db80030-905f-4039-a299-4818d1c9faf9)

Feel free to reopen if it's still an issue.
