### ISSUE TITLE
Feature Request : Theming

### ISSUE THREAD

**Issue by rahulbhatia101** [oliverschwendener/ueli#759]
Hi Oliver,

Just simple things,

1. Auto Dark / Light mode ( Already implemented it in windows 10 using task scheduler, so just implement a option of "System Theme") in search box and in settings menu
2.  Blur / Acrylic effects options would give it good asthetics

Would appreciate your consideration

**Comment by drewauff** [comment]
I agree, but also the ability to change all fonts sizes too.

**Comment by frankie-tech** [comment]
Also font-weight, the results description is really hard to see sometimes

**Comment by drewauff** [comment]
After seeing the last update and lack of a response from the devs. It is blatantly obvious they are very much function over form, having said that, I don't think we will see any type of theming or gui customisation anytime soon or at all.

Its rather quite sad to be honest, its such a great up but by not letting users make it "ours". well lets just say its a missed oppurtunity.

**Comment by oliverschwendener** [comment]
> I don't think we will see any type of theming or gui customisation anytime soon or at all.

@drewauff Ueli has a color theme section in the settings, did you know that?

![image](https://user-images.githubusercontent.com/15727229/135744338-7b136012-abda-40fb-9c10-a4c7dee90e31.png)

**Comment by oliverschwendener** [comment]
For the acrylic blur, check out [this](https://github.com/oliverschwendener/ueli/issues/689) feature request and [this](https://github.com/oliverschwendener/ueli/issues/116).

**Comment by drewauff** [comment]
@oliverschwendener colors are one thing, but gui fonts are another, you have made it part of the way, why not go all the way. Surely it cant be that hard. Its all in a css and they are super easy to change.

If you dont want to do it, at least allow us to do it for ourselves, maybe config file or in the .app put the css so we can easily change it instead of having to decompile, change whatever values then recompile again hoping it will work.

Stubborn devs are exactly the thing that keep, potentially long term users, at bay. 

Developers need to listen to the users that care enough to post issues etc. 

Either way, as good as Ueli is, ill be sticking to dmenu-mac for the time being, maybe one day ill venture back.

**Comment by oliverschwendener** [comment]
@drewauff 
- _Why not go all the way?_
It was not an active decision against font customization. At the time when I implemented the color customization it just didn't come to my mind that somone wants to change the font. And of course it's a good idea to have this option of customization as well, there is nobody saying that this is not needed.

- _Surely it cant be that hard._
No it's probably not hard, but it takes time to implement it.

- _If you dont want to do it, at least allow us to do it for ourselves._
Of courese we want to allow the users to customize the UI to their likings. Again, it's just that until now nobody took their time to implement this feature.

- _Stubborn devs are exactly the thing that keep, potentially long term users, at bay._
What makes you think the developers working on this project are stubborn?

- _Developers need to listen to the users that care enough to post issues etc._
What makes you think we don't?

**Comment by frankie-tech** [comment]
I agree with @olivereisenhut, total theme customization isn't just a switch flip, especially if it wasn't in the original plan. Adding it in later takes serious thought to not, for lack of a better word, fuck it up. 

To be more collaborative about it, if I can get pointed in the right direction, I'd be more than happy to take a crack at it.

**Comment by oliverschwendener** [comment]
Thanks @frankie-tech for the offer, but not needed anymore ;) See https://github.com/oliverschwendener/ueli/commit/895e6df8afe33643718c5c51d21b923ac9d4cecc

**Comment by oliverschwendener** [comment]
Closing this issue as it's fixed in Ueli v9.0.0-alpha.2

- Automatic switch between dark and light appearance based on the Windows theme
- Support for different background materials: Acrylic, Mica, Tabbed

Here is an example screenshot:
![image](https://github.com/oliverschwendener/ueli/assets/15727229/2b684768-7b87-4b81-a9b2-211748e313b5)
