### ISSUE TITLE
If I execute Chrome as a command from UELI it becomes unresponsive

### ISSUE THREAD

**Issue by lefteriz** [oliverschwendener/ueli#838]
I have set up a shortcut **commandline tool** that opens chrome with a specific URL. In the following form:

`"C:\Program Files\Google\Chrome\Application\chrome.exe" "URL"`

The command launches normally Chrome on the specified URL and everything looks good. However after that, UELI becomes unresponsive, I can launch it through its shortcut (alt + spacebar) but anything I type gets ignored like there is no focus or its stuck. Occasionally it shows the message "Refreshing indices" but again it doesn't accept input from the keyboard.

The issue gets resolved if I close the Chrome window that UELI opened up. I guess it has to do something with creating a new process or something(?).

The same thing happens with every URL I tried in combination with launching Chrome. 

Moreover, I have tried doing the same thing with Firefox by invoking:

`"C:\Program Files\Mozilla Firefox\firefox.exe" "SAME URL" `

In this case it works as it should, i.e. it launches a Firefox window with the appropriate URL, and then I can still type in the search box of UELI nromally.

A little explanation on why I am not using straight ahead the "URL" option when creating shortcuts: The URL option uses the default browser (in my case Firefox) but I want to use Chrome for that specific URL since it doesn't work as it should in Firefox. Since there is no option to select a browser per URL shortcut (would be redundant I guess) I just though of invoking Chrome as a command as I would have done from the CLI.

**Comment by gspinoza** [comment]
Had same issue using Brave browser on MacOs.

Temporary Solution: used Workflows plug-in instead of Shortcuts.
you command will become: `\"C:\Program Files\Google\Chrome\Application\chrome.exe\" \"URL\"`

Disadvantage on MacOs, not sure about windows: The only disadvantage is that it will open the terminal too, as the instance of the chrome browser will be connected to the terminal session. This means that if you close the terminal it will quit your browser too. I solved this by using a separate apple script on Workflows.

**Comment by lefteriz** [comment]
Good reply, I will try that as a workaround, thanks!
