### ISSUE TITLE
Search in Google Drive (Streaming files)

### ISSUE THREAD

**Issue by drkdw** [oliverschwendener/ueli#840]
Hi!

Quick question, 

As spotlight doesn't allow me to search in Google Drive (streaming files) on Mac Monterey, I'm looking for an alternative way to do so.

I came across this tool but didn't find the setting to Index and search Google Drive but maybe I'm not turning on the right settings. I'm using the Google Drive - Stream Files and not Mirror files (as this will download the full shared Google Drive and this is around 200gb).

I'm looking forward to your reply!

**Comment by booi** [comment]
@drkdw did you ever resolve this issue? I primarily store documents in google drive and since the shift to streaming files, searching has stopped working

**Comment by drkdw** [comment]
Hi @booi, No I didn't resolve this issue. I already switched and now I'm using raycast(.com) very powerful, sleek and free.

**Comment by danitt** [comment]
> Hi @booi, No I didn't resolve this issue. I already switched and now I'm using raycast(.com) very powerful, sleek and free.

macOS only, and closed source, so more like "free until they say otherwise"

had a look at their Google Workspace plugin, which is how they might've worked around it, and looks like they might just be searching via web API, which ofc requires giving full Drive access to some random closed app - would make me a little uneasy to hand over the keys like that, without seeing under the hood

**Comment by booi** [comment]
@danitt is correct, looks like their google workspace extension requires all google drive permissions to work

<img width="512" alt="image" src="https://user-images.githubusercontent.com/709595/160021309-414d4f98-6e20-49e3-bbc2-bca51e2691fe.png">

I don't get it, is searching a network drive that hard?

**Comment by oliverschwendener** [comment]
I'll close this issue as there are no plans currently to add this feature.
