### ISSUE TITLE
When workflow is executed, cmd windows stays open. 

### ISSUE THREAD

**Issue by tonijeto** [oliverschwendener/ueli#857]
I would like to report issue that I noticed when I updated to the latest version of Ueli 8.18.1.
I have an workflow that closes all work related applications. Previously it worked fine, but now cmd windows are not closing after execution of command. 

I am using multiple commands like "taskkill/im slack.exe" and this is the result now: 
![image](https://user-images.githubusercontent.com/16349924/147653041-8bf76fdc-60a3-4efc-b425-d8550d765b30.png)

**Comment by weiw11** [comment]
A workaround to your issue as I encountered this as well.

Create a `.bat` file like this:

```bat
@echo off 
taskkill /IM "zoom.exe" /F 
taskkill /IM "slack.exe" /F
exit \B
```

On Ueli, instead of `Commandline Tool`, use `File path` and select the `.bat` file.

I think it's better as is. Otherwise if the user entered a command such as `ping google.com`, it will just exit without displaying the results for `Commandline Tool`. Trying to prevent it from closing automatically will also be harder in this case. @oliverschwendener , your thoughts?

**Comment by tonijeto** [comment]
I did as  per you instructions and it works. Much appreciated.
