### ISSUE TITLE
[feature request] Add Everything search support

### ISSUE THREAD

**Issue by waqashsn** [oliverschwendener/ueli#93]
Everything by Voidtools (http://www.voidtools.com/) is the fastest and most customizable search tool in my experience. The Khanhas fork (https://github.com/khanhas/ueli/wiki/Everything-mode) of Ueli has implemented it already. Please consider integrating Everything.

**Comment by chantisnake** [comment]
Everything has a very handy command line interface can be found here: https://www.voidtools.com/support/everything/command_line_interface/

**Comment by oliverschwendener** [comment]
Will look into this as soon as possible!

**Comment by alanaasmaa** [comment]
For an example Wox requires to install Everything as a service. I think this is best to be installed as service, but it would be awesome if it can be bundled with ueli installer (not sure how we should handle other OS).

Everything IS BEST and FASTEST so i think if it replaces ueli default search it would be awesome.

Here is an example how to use it *=>*
`C:\Users\AlanAasmaa\.ueli\es.exe -n 10 -s [search pattern]`

**Comment by oliverschwendener** [comment]
Currently I'm working on a total rewrite of the core to support async code (essential when executing 3rd party binaries or making http requests). I am planning to add a everything plugin by default but the user has to install everything and es by himself.

**Comment by oliverschwendener** [comment]
In the upcoming update I added an everything plugin. By default this plugin is deactivated because I expect most users not having installed everything on their computer. But if you installed everything (including CLI) on your computer you can activate this plugin and specify a prefix which is used to recognize if you want to use everything search. Additionally you have to specify the file path to "es.exe" (the everything CLI).

![image](https://user-images.githubusercontent.com/15727229/56474427-10abe800-647a-11e9-8bf8-8524b047a4ec.png)

This is how you would use the everything plugin then:

![image](https://user-images.githubusercontent.com/15727229/56474425-0984da00-647a-11e9-8e65-4484e85fbf7a.png)

If you want everything search to be default you can specify an empty string as prefix so everytime you search for something within ueli the everything plugin is used.

![image](https://user-images.githubusercontent.com/15727229/56474446-5963a100-647a-11e9-841b-ba7d52f1aa64.png)

This is how you would use the everyting plugin without any prefix:

![image](https://user-images.githubusercontent.com/15727229/56474451-608aaf00-647a-11e9-9ef3-99ae1649a756.png)

I hope this is what you guys have been looking for?

**Comment by chantisnake** [comment]
Thank you!

**Comment by waqashsn** [comment]
So has this been added in the currently available build? I looked for it but didn't find any option related to Everything search in Settings.

**Comment by oliverschwendener** [comment]
@waqashsn No not yet. This will be added in the next major update 8.0.0 which will be released in the next few weeks (I hope :P)

**Comment by oliverschwendener** [comment]
This is included in the newest [v8.0.0](https://github.com/oliverschwendener/ueli/releases/v8.0.0) release.
