### ISSUE TITLE
[feature request] For linux

### ISSUE THREAD

**Issue by zamgill** [oliverschwendener/ueli#94]
Hi! I love this app. Please create a linux version for this :smile:

**Comment by jcklpe** [comment]
Hey just wanted to put my support in for this feature. I currently work on Windows (personal laptop), linux (home cloud server), and mac (work laptop). I use Listary, Albert, and Alfred for these three and looking at this project it seems to cover most of the features I'd like to use, and if I could use a single app between all 3 I would be extremely happy.

**Comment by jcklpe** [comment]
Just wanted to say that I had to replace my windows laptop so I decided to give Ueli a whirl. It's great! I would love to have this on Linux even in a reduced capacity. I really just use my launcher for search engines (translating, image searching, etc), finding files and folders, running the occasional command, and quick calculations. 

This launcher has great visual design and is super snappy though. It would be awesome to have this on Linux. I realize that some of the more systems oriented stuff like system settings or systems commands might be a little bit harder to make compatibility for, but alfred, which is the albert clone for Linux I currently use, doesn't log any of the system settings stuff, and the shutdown and restart etc commands should be relatively simple to integrate, even if it was on an ad hoc basis by users through running a command shortcut. 

@oliverschwendener The visual design is on point!

**Comment by jcklpe** [comment]
I'm currently using Ueli full time on my mac and windows machines. If anyone is looking for a linux equivalent then I highly recommend [[Albert]](https://github.com/albertlauncher/albert). 

It has a very similar feature set and set-up style. I would really prefer to use Ueli on all my OS or use Albert on all my OS, but for now this is a pretty decent stop gap and there's not a ton of confusion between using the two, though I do prefer how Albert allows websearches with automatic trigger words rather than requiring the "?" mark to trigger a websearch.

**Comment by jcklpe** [comment]
I know this is a big ask but this feature would be great to have. Is there anyway that I could help out with this? I'm not a very good developer but I like fiddling around with my home linux machine. Is it simply a matter of setting up Electron to make a Linux build? Or do other things need to be changed?

**Comment by oliverschwendener** [comment]
I would suggest that you first try to get the app running on a linux machine:

1. Clone the repo
2. Install node 12 and yarn
3. Install the dependencies with `yarn install`
4. Start the watcher (transpiling TS to JS files) with `yarn bundle:watch`
5. Start the app with `yarn start`

Probably it won't work out of the box because it only checks if the app is running on Windows and if not it assumes it is on macOS.

Challenges you might face:
- Where to read the installed apps from
- How to generate an icon out of an app
- How to perform operating system commands like shutdown/restart/etc
- Where to read operating system setting from

**Comment by jcklpe** [comment]
@oliverschwendener Awesome, I'll try to build and install it and I'll report back. 

Even if the functionality is limited in those ways you mention I'd still like to use it instead of Albert because I like having a consistent user experience between my OS and because I think your app looks nice and is easier to configure the way I like. 

I honestly mostly just use it to launch short cuts, do web searches, initiate scripts, and do some quick math. But it does all that stuff super well!

**Comment by oliverschwendener** [comment]
@jcklpe Make sure to checkout the `dev` branch

**Comment by PunchEnergyFTW** [comment]
I'd love to have a Linux version aswell! 

Are there any plans for it ?

**Comment by zohozer** [comment]
Yes, Still looking for the Linux version of Ueli.

**Comment by LeonardsonCC** [comment]
Hi!
There anyone working on this?
I was reading the code and there's a lot of work to do, the bookmarks, application search and all... if anyone wants help

**Comment by oliverschwendener** [comment]
As far as I know, there is nobody working on this right now. I would love to work on this but just can't find time. If I can help in any way let me know.

**Comment by LeonardsonCC** [comment]
I'm starting to work on this, maybe it take some time, but I'll try!

**Comment by freedsny** [comment]
Que tal esta app: https://www.fluentsearch.net/
                            https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search/distribution_groups/daily

**Comment by yurinnick** [comment]
I actually made some progress, now the app actually starts and doesn't immediately explode in pieces :) Still, quite far from full functionality since I get return empty results here and there.

![photo_2021-08-08_03-12-40](https://user-images.githubusercontent.com/2941035/128628611-128e22fc-eee4-41fb-90a2-9d572da9dc79.jpg)

**Comment by gerroon** [comment]
@yurinnick Any progress with this? It would be so great to have  it in Linux.

**Comment by lucasew** [comment]
Someone already tried [1].

I didn't inspect the code yet.

[1] https://github.com/oliverschwendener/ueli/pull/854

**Comment by LeonardsonCC** [comment]
Hey, anyone knows why this [PR](https://github.com/oliverschwendener/ueli/pull/854) was closed?
I just tested the fork here using Arch Linux and KDE as DE and the core functions are working great!

**Comment by t18n** [comment]
Any news on this guys? :)

**Comment by oliverschwendener** [comment]
Ueli v9 supports linux out of the box, but every extension has to add their support separately. I consider this to be fixed. Please open separate feature requests if you want to request linux support for an extension.

**Comment by oliverschwendener** [comment]
The latest beta release includes support for searching applications on Linux, thanks to @ke1v!

https://github.com/oliverschwendener/ueli/releases/tag/v9.0.0-beta.0
